[versions]
agp = "8.13.2"

kotlin = "2.2.0"

composeBom = "2025.12.01"

activityCompose = "1.12.2"
appcompat = "1.7.1"
coreKtx = "1.17.0"
securityCrypto = "1.1.0"

lifecycleRuntimeKtx = "2.10.0"
lifecycleViewModelCompose = "2.10.0"

#material = "1.13.0"
#material3 = "1.4.0"

firebaseAuth = "23.2.1"
firebaseFirestoreKtx = "25.1.4"
gms = "4.4.4"

roomKtx = "2.8.4"
workRuntimeKtx = "2.11.0"
datastore = "1.2.0"
documentfile = "1.1.0"

navigation = "2.9.6"

hilt = "2.57.2"
hiltWork = "1.3.0"
hiltNavigationCompose = "1.3.0"

kotlinSerialization = "1.9.0"
#kotlinxCoroutinesGuava = "1.10.2"
#guava = "33.5.0-android"

timber = "5.0.1"
itextg = "5.5.10"

junit = "4.13.2"
androidxJunit = "1.3.0"
espressoCore = "3.7.0"
robolectric = "4.16"

runtimeSaveable = "1.10.0"
foundationLayout = "1.10.0"


[libraries]
# ---------- Core AndroidX ----------
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

# ---------- Compose ----------
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
#androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

androidx-compose-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-saveable", version.ref = "runtimeSaveable" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }

# ---------- Lifecycle ----------
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewModelCompose" }

# ---------- Activity ----------
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# ---------- Navigation ----------
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# ---------- Room ----------
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }

# ---------- WorkManager ----------
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

# ---------- Data ----------
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }

# ---------- Firebase ----------
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuth" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }

# ---------- Hilt ----------
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# ---------- Kotlin ----------
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
#kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutinesGuava" }

# ---------- Utilities ----------
#guava = { module = "com.google.guava:guava", version.ref = "guava" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
itextg = { module = "com.itextpdf:itextg", version.ref = "itextg" }

# ---------- Testing ----------
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
